#!/bin/bash -e

echo "=> Build CouchDB source code"

if [ ! -z "$SOURCE_BRANCH" ];then
    ENV_OPT="-e SOURCE_BRANCH=$SOURCE_BRANCH"
fi

if [ ! -z "$GIT_TAG" ];then
    ENV_OPT="$ENV_OPT -e GIT_TAG=$GIT_TAG"
fi

#docker run --volume=`pwd`/../..:/usr/src/couchdb --volume=`pwd`/build.sh:/build.sh --entrypoint=/build.sh $ENV_OPT alpine:edge
docker run -it --volume=`pwd`/../..:/usr/src/couchdb --volume=`pwd`/build.sh:/build.sh --entrypoint=sh $ENV_OPT alpine
exit $?
